"""Script to generate realistic offline sample data for BS & Hype Analyzer.

Creates:
1. data/raw/sample_rss_feeds.json (10 outlets × 15 articles = 150 realistic items)
2. data/raw/sample_youtube_transcript.json (1 multi-modal financial influencer audio transcript)
"""

import json
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
RAW_DIR = PROJECT_ROOT / "data" / "raw"
RAW_DIR.mkdir(parents=True, exist_ok=True)

# 10 Outlets
OUTLETS = [
    {"id": "bloomberg_tech", "name": "Bloomberg Technology", "category": "Technology & Finance", "bias_label": "Institutional Financial", "weight": 1.0},
    {"id": "reuters_biz", "name": "Reuters Business", "category": "Macro & Markets", "bias_label": "Wire Service (Baseline)", "weight": 0.9},
    {"id": "cnbc_markets", "name": "CNBC Markets", "category": "Financial Media", "bias_label": "Sensational Financial Broadcast", "weight": 1.2},
    {"id": "yahoo_finance", "name": "Yahoo Finance", "category": "Retail Finance", "bias_label": "Retail Aggregator", "weight": 1.1},
    {"id": "techcrunch_ai", "name": "TechCrunch AI & Startups", "category": "Tech Startups", "bias_label": "Venture Hype Cycle", "weight": 1.3},
    {"id": "the_verge", "name": "The Verge Tech", "category": "Tech Journalism", "bias_label": "Consumer Tech Critique", "weight": 1.0},
    {"id": "coindesk_crypto", "name": "CoinDesk Crypto News", "category": "Crypto & Web3", "bias_label": "Speculative Crypto", "weight": 1.4},
    {"id": "financial_times", "name": "Financial Times Markets", "category": "Institutional Finance", "bias_label": "Institutional Analysis", "weight": 0.9},
    {"id": "marketwatch_top", "name": "MarketWatch Bulletins", "category": "Retail Trading", "bias_label": "Retail Momentum", "weight": 1.2},
    {"id": "wsj_markets", "name": "Wall Street Journal Markets", "category": "Financial News", "bias_label": "Mainstream Financial", "weight": 0.95},
]

# High, medium, and low hype templates across tech, markets, crypto, macro
ARTICLES_DATA = {
    "bloomberg_tech": [
        ("Apple Expands AI Infrastructure With Multi-Billion Data Center Commitment",
         "Apple Inc. is committing $5 billion over three years to proprietary enterprise server infrastructure, expanding its private cloud computation capabilities as institutional demand grows.",
         0.18),
        ("Nvidia Revenue Growth Moderates to 45% as Cloud Providers Optimize GPU Clusters",
         "Nvidia Corp. reported quarterly sales of $32.4 billion, meeting analyst forecasts while hyperscalers such as Microsoft and Google focus on capital expenditure return cycles.",
         0.22),
        ("TSMC Accelerates 2nm Production Timeline Ahead of Global Fab Deployments",
         "Taiwan Semiconductor Manufacturing Co. confirmed initial risk production for next-generation 2nm silicon remains on schedule across Taiwan and Arizona facilities.",
         0.15),
        ("Enterprise Software Valuation Multiples Contract Following Mixed Earnings",
         "Valuation multiples for SaaS companies compressed by 12% in the second quarter as corporate enterprise budgets tightened scrutiny on generative AI pilot budgets.",
         0.20),
        ("OpenAI In Talks for New Funding Round Valued Above $150 Billion",
         "OpenAI is in preliminary discussions with venture syndicates and sovereign wealth funds to raise additional equity, valuing the startup at approximately $150 billion.",
         0.38),
        ("Semiconductor Supply Chain Faces Tight Substrate Packaging Constraints",
         "High-bandwidth memory packaging capacity remains constrained at major foundries, limiting shipment velocities for advanced AI accelerator chips into Q4.",
         0.16),
        ("European Regulators Scrutinize Cloud Computing Licensing Agreements",
         "The European Commission launched inquiries into competitive practices surrounding enterprise hyper-scaler licensing terms and software bundling.",
         0.19),
        ("Autonomous Vehicle Fleets Surpass 10 Million Commercial Driverless Miles",
         "Waymo and rival robotaxi operators reached a combined 10 million paid commercial driverless passenger miles in Phoenix and San Francisco test markets.",
         0.24),
        ("Quantum Computing Startups Pivot Toward Hybrid Classical-Quantum Architectures",
         "Faced with extended quantum error correction timelines, venture-backed hardware developers are reorienting near-term roadmaps toward hybrid co-processing.",
         0.28),
        ("Wall Street Banks Deploy Local LLMs for Algorithmic Trade Compliance Audits",
         "JPMorgan and Goldman Sachs have implemented privately hosted language models to monitor institutional trading desk communications for regulatory compliance.",
         0.21),
        ("Cybersecurity Budget Growth Slows to Single Digits in Annual Corporate CFO Survey",
         "Corporate chief information officers reported a median cybersecurity spending increase of 6.2%, down from 11.5% in the preceding fiscal cycle.",
         0.14),
        ("Venture Capital Funding in Robotics Increases 28% Driven by Warehouse Automation",
         "Logistics automation attracted $3.8 billion in early-stage financing, defying broader tech venture contractions as fulfillment centers automate physical workflows.",
         0.25),
        ("Meta Inks Multi-Year Clean Energy Purchase Agreements for AI Data Hubs",
         "Meta Platforms signed 1.2 gigawatts of geothermal and solar power contracts to supply energy for expanding neural network training centers across the American Midwest.",
         0.17),
        ("Smartphone Replacement Cycles Extend to 41 Months Globally",
         "Global handset shipments stabilized with consumer upgrade cycles extending to an average of 41 months, despite promotional AI software features.",
         0.20),
        ("Tech Sector Debt Issuance Reaches Record High Amid Capital Expenditure Expansion",
         "Large-cap technology corporations issued $48 billion in investment-grade corporate bonds to fund server real estate, data centers, and advanced silicon stockpiles.",
         0.19),
    ],
    "reuters_biz": [
        ("Federal Reserve Holds Benchmark Rate Steady at 5.25%-5.50% Citing Inflation Data",
         "The Federal Open Market Committee maintained its benchmark overnight borrowing rate in a targeted range of 5.25%-5.50%, noting balanced risks in employment and price stabilization.",
         0.10),
        ("US Nonfarm Payrolls Rose by 175,000 in August; Unemployment Rate Holds at 4.1%",
         "The Bureau of Labor Statistics reported nonfarm payroll growth of 175,000 jobs last month, broadly consistent with consensus estimates of 165,000.",
         0.08),
        ("European Central Bank Cuts Policy Rate by 25 Basis Points to Support Growth",
         "The ECB lowered its deposit facility rate by a quarter-point to 3.50% following moderating wage growth across eurozone member economies.",
         0.11),
        ("Oil Prices Settle Lower as Supply Concerns Ease and Global Inventories Rise",
         "Brent crude futures declined 1.8% to settle at $74.20 a barrel amid higher crude exports from non-OPEC producers and tepid manufacturing indicators.",
         0.12),
        ("Consumer Price Index Rose 2.7% Year-Over-Year, Matching Consensus Projections",
         "Core CPI, which excludes volatile food and energy costs, increased 0.2% on a monthly basis, aligning with economists' expectations and stabilizing Treasury yields.",
         0.09),
        ("Treasury 10-Year Yield Steady at 3.88% Following Treasury Refunding Auction",
         "Yields on the benchmark 10-year US Treasury note traded within a narrow band following strong primary dealer absorption at the monthly auction.",
         0.10),
        ("Global Container Shipping Rates Decline 6% on Transpacific Trade Lanes",
         "Spot container freight rates from Shanghai to Los Angeles fell 6% week-on-week, reflecting easing port congestion and normalized post-peak season container flow.",
         0.13),
        ("Boeing Reaches Tentative Labor Agreement with Commercial Aircraft Machinist Union",
         "Boeing Co. and union leadership finalized terms on a proposed 25% general wage increase over four years, subject to member ratification votes.",
         0.15),
        ("Japan Export Growth Moderates Amid Currency Volatility and Soft Overseas Demand",
         "Japanese export volumes expanded 5.6% year-on-year in the latest trade bulletin, supported by automotive shipments while machinery orders slowed.",
         0.11),
        ("Commercial Real Estate Delinquency Rates Rise Modestly to 1.8% in Q2",
         "Metropolitan commercial office loan default rates increased slightly to 1.8%, while industrial logistics and multifamily portfolios maintained low default ratios.",
         0.14),
        ("Auto Industry EV Transition Paces Below Initial Forecasts as Hybrid Sales Rise",
         "Major automakers reported pure battery electric vehicle sales grew 8% while plug-in hybrid electric vehicles expanded 34% across North American dealerships.",
         0.17),
        ("World Bank Maintains 2026 Global Economic Growth Forecast at 2.6%",
         "The multilateral lender projected steady global GDP expansion of 2.6%, highlighting fiscal constraints in developing economies and resilient consumer activity in North America.",
         0.10),
        ("Copper Futures Dip on Inventory Build in London Metal Exchange Warehouses",
         "LME copper prices slipped 0.9% to $9,120 per metric ton as visible exchange inventories reached an eight-month seasonal peak.",
         0.12),
        ("Retail Sales Show Modest 0.3% Increase as Consumers Prioritize Essential Goods",
         "Department of Commerce data indicated consumer spending expanded 0.3% in July, propelled by grocery and online e-commerce categories.",
         0.13),
        ("Gold Prices Consolidate Near $2,500 an Ounce Ahead of Central Bank Speeches",
         "Spot bullion traded flat at $2,498 per ounce as precious metals traders awaited macroeconomic guidance from Jackson Hole economic symposium remarks.",
         0.15),
    ],
    "cnbc_markets": [
        ("CRASH OR RALLY? Wall Street Strategists Issue Urgent Warning as Volatility Explodes!",
         "Top analysts warn investors are sleepwalking into a massive market trap! Insiders reveal unprecedented portfolio rotation that could trigger an overnight bloodbath or historic breakout.",
         0.84),
        ("Jim Cramer: Why This Revolutionary Stock Could Be The Next Nvidia Overnight",
         "Jim Cramer reveals the single game-changer stock that every retail investor must buy before the institutional crowd takes it to the moon!",
         0.88),
        ("WARNING: Tech Giants Face Massive AI Bloodbath as Capital Expenditures Skyrocket",
         "Sources say big tech spending is totally out of control! Analysts claim a violent 20% correction is guaranteed unless earnings double instantly.",
         0.79),
        ("Billionaire Investor Warns of Unprecedented Bubble: 'Get Ready for the Shock of Your Life'",
         "A legendary hedge fund titan claims the current stock market setup is identical to 1999 and guarantees catastrophic losses for passive index holders.",
         0.82),
        ("Is the Fed Making a Catastrophic Policy Mistake? Market Whispers Predict Chaos!",
         "Insiders warn that Jerome Powell is moving dangerously late, and many believe an emergency rate slash is the only thing standing between retail wealth and ruin.",
         0.76),
        ("Forget Apple and Microsoft: This Secret Loophole Stock Will 10x in 2026!",
         "Experts agree that small-cap artificial intelligence plays are primed for an explosive parabolic surge that will shock traditional Wall Street analysts.",
         0.91),
        ("Bitcoin Skyrockets Toward Historic All-Time High as Institutional FOMO Ignites!",
         "Crypto enthusiasts are stunned as Bitcoin shatters resistance! Top investors agree a $150,000 moonshot is mathematically guaranteed this quarter.",
         0.83),
        ("The Magnificent Seven Trap: Why You Must Sell Your Big Tech Shares RIGHT NOW!",
         "Urgent warning from top wealth advisors: retail traders are dangerously overexposed to overhyped tech names, and a brutal crash is imminent!",
         0.86),
        ("Revolutionary Biotech Miracle: Could This Mystery Micro-Cap Cure Aging and 50x?",
         "Insiders suggest clinical trial whispers could transform this unknown penny stock into a global pharmaceutical powerhouse overnight.",
         0.92),
        ("Stock Market Breakout! Why the S&P 500 Is Primed for an Unstoppable Melt-Up",
         "Bullish momentum indicators are flashing unprecedented green signals, and top traders say bears are about to get completely annihilated!",
         0.78),
        ("SHOCKING Warning From Morgan Stanley: Tech Multiples Face Brutal Reality Check",
         "Experts predict a painful paradigm shift in equity valuations that will wipe out trillions in paper gains for speculative retail portfolios.",
         0.75),
        ("Tesla Robotaxi Reveal: The Paradigm Shift That Could Send Shares Soaring 300%!",
         "Elon Musk promises a historic milestone that will revolutionize autonomous transport forever. Analysts claim this is a once-in-a-lifetime wealth opportunity.",
         0.87),
        ("Urgent Warning for Retirees: Cash Is Trash and Your 401(k) Is in Grave Danger!",
         "Financial gurus warn that inflation and market debasement are silently destroying retirement savings. Discover the guaranteed defensive playbook now.",
         0.80),
        ("The Energy Supercycle Is Here: 3 Breakout Oil Stocks Ready to Explode Higher!",
         "Market insiders reveal why global crude deficits will cause prices to skyrocket, delivering massive windfall dividends to retail investors.",
         0.74),
        ("Don't Miss Out! The Secret AI Infrastructure Play That Wall Street Is Hiding From You",
         "Everyone is talking about microchip manufacturers, but this unheralded utility provider could deliver the biggest returns of the decade!",
         0.89),
    ],
    "yahoo_finance": [
        ("Nvidia vs AMD: Which Artificial Intelligence Giant Is the Better Buy Right Now?",
         "Investors are weighing Nvidia's dominant market share against AMD's discounted multiple, with analysts debating who will capture the next enterprise wave.",
         0.42),
        ("3 Dividend Aristocrats That Can Pay Your Bills For Life in Any Economy",
         "Building passive dividend income through dependable consumer staple companies that have increased annual payouts for over 25 consecutive years.",
         0.46),
        ("Cathie Wood Sells Tesla Shares to Double Down on High-Growth Genomic Innovator",
         "Ark Invest disclosed trades trimming Tesla holdings while acquiring 250,000 shares of gene-editing biotech firm ahead of pivotal phase 2 trials.",
         0.48),
        ("Why S&P 500 Index Funds Remain the Undisputed Core of Wealth Building",
         "Historical analysis demonstrates why low-cost broad index tracking consistently outperforms over 85% of active mutual fund managers over 15-year spans.",
         0.31),
        ("Palantir Technologies Gains 8% Following Major Government Defense Contract Renewal",
         "Palantir secured a $480 million Pentagon software expansion, bolstering commercial enterprise momentum and driving retail trading volume.",
         0.39),
        ("Housing Market Freeze: Mortgages Rates Hover at 6.5% as Buyers and Sellers Clash",
         "Existing home sales contracted 1.2% in June as locked-in low mortgage rates discourage current owners from listing, preserving tight inventory.",
         0.35),
        ("Could This Under-the-Radar Quantum Computing Stock Surge 500% by 2028?",
         "Speculative growth investors are watching early-stage hardware players as quantum algorithms approach practical commercial utility in chemistry.",
         0.68),
        ("Warren Buffett's Berkshire Hathaway Sells Half Its Apple Stake: What Should You Do?",
         "The Oracle of Omaha raised Berkshire's cash pile to a record $277 billion, sparking widespread debate on equity valuations and consumer tech demand.",
         0.44),
        ("Amazon AWS Operating Margins Surge as Cost Optimization Phase Concludes",
         "Cloud revenue grew 19% year-over-year with operating margins expanding to 38%, underscoring cloud operational efficiency and custom chip deployment.",
         0.28),
        ("Is Bitcoin Headed to $100,000 or $40,000? Top Crypto Analysts Battle It Out",
         "Bull and bear cases clash following the Bitcoin halving event, with ETF inflows driving institutional liquidity while macro uncertainty lingers.",
         0.58),
        ("Retail Traders Pour Millions Into Meme Stock Comeback as Volatility Spikes",
         "Social media forums drove renewed call option volume in heavily shorted retail names, causing sharp intraday price swings and trading halts.",
         0.65),
        ("Treasury Yield Curve Inversion Deepens: History Says Recession Watch Is On",
         "The 2-year and 10-year Treasury yield curve spread remains negative, historically serving as a leading indicator of macroeconomic deceleration.",
         0.33),
        ("5 Top Artificial Intelligence ETFs for Tech Investors Looking to Diversify",
         "An examination of expense ratios, underlying semiconductor weightings, and thematic robotics exposure across leading tech ETF offerings.",
         0.36),
        ("SoFi Technologies Jumps as Personal Loan Volume and Banking Deposits Expand",
         "The digital bank reported adjusted net revenue growth of 20% alongside accelerating deposit growth and expanding net interest margins.",
         0.32),
        ("Is Intel's Foundry Turnaround Realistic? Analysts Weigh Multi-Billion Subsidies",
         "With CHIPS Act financing confirmed, Wall Street debates whether Intel's manufacturing division can successfully win external high-volume fab clients.",
         0.37),
    ],
    "techcrunch_ai": [
        ("This Stealth AI Startup Just Raised $200M to Build the Ultimate Foundation Model",
         "Ex-DeepMind researchers launched a revolutionary new architecture that promises to completely disrupt transformers and solve AGI forever!",
         0.85),
        ("YC Demo Day Highlights: 85% of New Startups Are Autonomous AI Agent Platforms",
         "Founders claim their autonomous agent swarms will replace human engineering teams and revolutionize software development within six months.",
         0.78),
        ("Venture Capitalists Are Pouring Billions Into Generative Video: The Next Trillion-Dollar Frontier",
         "Prominent venture partners predict Hollywood will be completely automated by generative diffusion models, creating a paradigm shift in entertainment.",
         0.81),
        ("Anthropic Unveils Claude 3.5 Sonnet Artifacts, Challenging Coding Benchmarks",
         "The new frontier model achieves 92.0% on HumanEval, introducing an interactive UI for real-time frontend generation and code execution.",
         0.45),
        ("Why 'Vibe Coding' and Autonomous Workflows Are Replacing Traditional Software Engineering",
         "Silicon Valley luminaries claim natural language is the only programming language left, promising unprecedented developer productivity gains.",
         0.72),
        ("Mistral AI Launches Lightweight Open-Weight Models for On-Device Inference",
         "The French AI unicorn released compact Apache 2.0 licensed models optimized for running locally on consumer laptops and edge hardware.",
         0.30),
        ("Is the Generative AI ROI Bubble About to Burst? Early Enterprise Customers Push Back",
         "Corporate IT leaders report skepticism over subscription seat pricing, noting high proof-of-concept churn rates and hallucination risks.",
         0.48),
        ("Robotics Startup Figure AI Deploys Humanoid Workers in Automotive Assembly Plants",
         "Humanoid robots powered by multimodal neural networks completed initial autonomous bin-picking tasks at BMW's Spartanburg manufacturing facility.",
         0.52),
        ("Open-Source AI Communities Outpace Proprietary Labs on Fine-Tuning Efficiency",
         "Researchers show low-rank adaptation (LoRA) and quantized architectures allow single-GPU training runs that rival massive proprietary clusters.",
         0.34),
        ("Startup Claims Its Revolutionary AI Architecture Uses 99% Less Electricity",
         "Founders say their biologically inspired neuromorphic chip will eradicate AI data center power bottlenecks overnight, shocking competitors.",
         0.83),
        ("Google DeepMind Introduces AlphaFold 3: Modeling All Molecules of Life",
         "The landmark research paper expands biological prediction from protein structures to DNA, RNA, ligands, and complex chemical modifications.",
         0.22),
        ("The Autonomous AI Agent Hype Cycle: Are We Chasing Science Fiction?",
         "Industry veteran engineers dissect the reality behind autonomous agents, showing reliable multi-step task completion remains elusive in production.",
         0.41),
        ("AI Chip Startup Enters Unicorn Club With $1.5B Valuation on Next-Gen Silicon",
         "Backers claim their custom tensor accelerator delivers 10x throughput over industry standards, promising to break Nvidia's monopoly.",
         0.77),
        ("Databricks Acquires Open-Source Data Management Startup for $100M",
         "The deal bolsters enterprise tabular intelligence and governance tools for enterprise clients managing enterprise data lakes.",
         0.26),
        ("Synthetic Data Startups Surge as Frontier Model Training Hits the Human Data Wall",
         "With public internet scrapable text largely exhausted, AI labs are betting billions on synthetic mathematical and reasoning datasets.",
         0.54),
    ],
    "the_verge": [
        ("The AI Hype Machine Is Selling Us a Sci-Fi Dream That Doesn't Work Yet",
         "From broken AI pins to glitchy smart glasses, tech executives are hyping unfinished prototypes as revolutionary breakthroughs.",
         0.62),
        ("Apple Intelligence Hands-On: Modest Quality-of-Life Tools, Not a Sci-Fi Revolution",
         "Apple's on-device writing tools and notification summaries are practical, but anyone expecting a sentient assistant will be sorely disappointed.",
         0.42),
        ("Humane AI Pin and Rabbit R1 Disasters Prove Dedicated AI Gadgets Are Premature",
         "Hardware teardowns and field reviews reveal why smartphone apps still crush slow, overheating, voice-only wearable AI gadgets.",
         0.55),
        ("Microsoft Recalls Controversial Windows Copilot+ Recall Feature to Fix Security Flaws",
         "Following cybersecurity backlash over unencrypted screenshot storage, Microsoft postponed the wider rollout of its automated screen recording feature.",
         0.35),
        ("Google Search Is Overrun With AI Slop and Bogus SEO Spam",
         "Users complain that search queries return generative spam and hallucinated answers advising people to put glue on pizza.",
         0.58),
        ("Sony Announces PlayStation 5 Pro at $700: AI Upscaling Without a Disc Drive",
         "The high-end console upgrade introduces PSSR machine learning upscaling, but gamers question the steep price tag for marginal fidelity gains.",
         0.38),
        ("EU Slaps Tech Giants With Massive Digital Markets Act Non-Compliance Inquiries",
         "European antitrust authorities target app store policies and default browser screens, demanding interoperability from ecosystem gatekeepers.",
         0.28),
        ("Tesla Cybertruck Owners Face Build Quality Woes and Recall Notices",
         "Stainless steel panels and accelerator pedal covers draw regulatory scrutiny as consumer complaints highlight early manufacturing defects.",
         0.45),
        ("OpenAI's o1 Reasoning Model: Impressive at Math, Still Prone to Wild Hallucinations",
         "Testing the chain-of-thought system reveals genuine breakthroughs in complex logic, but it still makes up confident falsehoods on basic trivia.",
         0.39),
        ("Why Every Single Tech Company Is Forcing an AI Assistant Down Your Throat",
         "Whether you're shopping for groceries or formatting a spreadsheet, venture-backed companies are shoehorning chatbots nobody asked for.",
         0.64),
        ("Bluesky and Mastodon Surge as Users Flee Commercial Social Media Algorithmic Feeds",
         "Decentralized social networking protocols gain traction among journalists and tech enthusiasts seeking open, non-monetized community platforms.",
         0.36),
        ("The Electric Vehicle Charging Infrastructure Nightmare Still Isn't Fixed",
         "Broken CCS plugs, confusing billing apps, and slow maintenance continue to plague road trippers outside of Tesla's Supercharger network.",
         0.48),
        ("Steam Deck OLED Review: The Best Portable Gaming Hardware Gets Even Better",
         "Valve's mid-cycle hardware refresh delivers gorgeous color contrast, substantially longer battery longevity, and cooler thermals.",
         0.25),
        ("Spotify Raises Subscription Prices Again While Pushing Video Podcasts and Audiobooks",
         "The streaming audio giant increases standard monthly premiums to $11.99 in its ongoing effort to achieve sustainable operational profitability.",
         0.22),
        ("Federal Trade Commission Takes Aim at Deceptive AI Marketing Claims and 'Fake Reviews'",
         "Regulators issue stern warnings to startups claiming miraculous artificial intelligence capabilities without verified scientific benchmarks.",
         0.33),
    ],
    "coindesk_crypto": [
        ("BITCOIN 100X MOONSHOT: Whales Accumulate as Analysts Predict $500,000 Supercycle!",
         "Urgent alerts flash across on-chain trackers! Insiders say sovereign nations are secretly buying Bitcoin before a massive supply shock sends prices to the moon!",
         0.94),
        ("Ethereum Layer-2 Gas Fees Drop 90% Following Dencun Upgrade Implementation",
         "Blob transactions introduced in EIP-4844 have slashed average rollup transaction costs on Arbitrum and Base from $0.40 to less than $0.02.",
         0.20),
        ("MEMECOIN MANIA: This Dog Coin Surged 5,000% Overnight—Is It the Next Dogecoin?",
         "Speculative traders are pouring life savings into viral token contracts, driven by TikTok hype and influencers promising guaranteed wealth.",
         0.93),
        ("Solana DeFi Total Value Locked Crosses $5 Billion Amid High-Throughput DEX Volume",
         "Daily decentralized exchange transactions on Solana briefly surpassed Ethereum mainnet, driven by fast settlement speeds and active automated market makers.",
         0.35),
        ("SEC Approves Spot Ethereum Exchange-Traded Funds for Public US Exchange Trading",
         "The Securities and Exchange Commission granted regulatory approval for eight spot ETH ETFs, opening direct regulated institutional capital access.",
         0.18),
        ("MASSIVE BLOODBATH: $800 Million Liquidated in Hours as Crypto Market Crashes!",
         "Overleveraged derivative positions were wiped out in a sudden cascade, leaving retail day traders reeling from violent 15% flash dips.",
         0.88),
        ("Top Crypto Trader Who Predicted 2021 Peak Issues Urgent Warning: 'Get Ready to Dump!'",
         "Insiders warn of an impending macroeconomic collapse that will wipe out alternative tokens, claiming only stablecoins will survive the coming winter.",
         0.87),
        ("Tether Reports $5.2 Billion Net Profit in First Half of 2026 Backed by US Treasuries",
         "The USDT stablecoin issuer disclosed $97 billion in direct US Treasury holdings, generating record interest yield while market capitalization hit $118 billion.",
         0.21),
        ("DeFi Protocol Suffers $45 Million Flash-Loan Exploit Due to Price Oracle Manipulation",
         "Smart contract auditors identified an unchecked reentrancy vulnerability in an automated liquidity pool, leading to immediate token drainage.",
         0.29),
        ("Crypto Influencers Accused of Orchestrating Multi-Million Dollar Pump-and-Dump Scheme",
         "Federal prosecutors unsealed indictments against five social media personalities who allegedly dumped unvetted tokens onto unsuspecting followers.",
         0.69),
        ("Federal Reserve Governor Reiterates Skepticism Over Central Bank Digital Currency",
         "Speaking at a banking conference, officials stated privacy concerns and established commercial banking rails negate the immediate need for a digital dollar.",
         0.16),
        ("Web3 Gaming Token Explodes 300% as Speculators Bet on Paradigm-Shifting Metaverse Game",
         "Promoters claim this blockchain title will replace triple-A gaming studios and revolutionize digital ownership, promising massive passive yield.",
         0.86),
        ("Institutional Bitcoin Custody Inflows Accelerate Across Major Wealth Management Wirehouses",
         "Financial advisors at Morgan Stanley and Wells Fargo began offering spot Bitcoin allocations to accredited high-net-worth wealth clients.",
         0.28),
        ("Zero-Knowledge Proofs: The Cryptographic Breakthrough Powering Scalable Privacy",
         "Developers explain how zk-SNARKs and recursive proving systems allow trustless computational verification without revealing sensitive financial underlying data.",
         0.24),
        ("URGENT: Ripple Lawsuit Final Judgment Delivered! XRP Army Celebrates Historic Victory!",
         "Enthusiasts declare complete regulatory vindication as court orders civil fine, with community influencers guaranteeing an imminent parabolic rally.",
         0.85),
    ],
    "financial_times": [
        ("Global Central Banks Navigate Divergent Monetary Policy Paths Amid Sticky Inflation",
         "With the Federal Reserve and ECB pacing interest rate adjustments independently, currency volatility has prompted multinational treasurers to hedge FX exposure.",
         0.16),
        ("Private Equity Exits Plummet 30% as Bid-Ask Spread Between Sponsors and Buyers Persists",
         "Institutional investors report a severe slowdown in capital distributions as buy-out sponsors resist writing down portfolio valuations established during peak 2021 cycles.",
         0.18),
        ("Sovereign Debt Burden Reaches 100% of Global GDP, IMF Fiscal Monitor Warns",
         "The International Monetary Fund urged finance ministries to consolidate fiscal deficits, warning that elevated long-term interest rates increase debt servicing strains.",
         0.14),
        ("Japanese Yen Carry Trade Unwind Triggers Global Equities Volatility",
         "The Bank of Japan's rate hike spurred rapid closing of short yen funding positions, sending ripples through leveraged equity and sovereign bond markets worldwide.",
         0.19),
        ("Pharmaceutical M&A Accelerates as Patent Cliff Looms for Blockbuster Biologics",
         "Top drug manufacturers deployed $65 billion in acquisition capital during H1 to replenish clinical pipelines before major immunology and oncology patents expire.",
         0.15),
        ("China's Real Estate Restructuring Faces Protracted Liquidity Impasse",
         "Municipal government property buyback initiatives have seen modest uptake as developers struggle to service offshore bonds and finish presold housing inventory.",
         0.17),
        ("Commodity Trading Houses Record Second Most Profitable Year on Energy Price Spreads",
         "Mercuria, Trafigura, and Vitol captured significant arbitrage margins across liquefied natural gas delivery contracts and refined petroleum shipping routes.",
         0.14),
        ("UK Gilts Steady as Chancellor Outlines Medium-Term Fiscal Responsibility Framework",
         "HM Treasury reaffirmed strict borrowing rules to reassure international gilt investors ahead of the upcoming autumn budget expenditure review.",
         0.12),
        ("Venture Capital Returns Fall Below Public Equity Indices Over 10-Year Horizon",
         "Pension trustees re-evaluate alternative asset allocations as Cambridge Associates data shows venture capital benchmark returns lagging the S&P 500.",
         0.22),
        ("European Luxury Goods Sector Grapples With Weakening Discretionary Demand",
         "Kering and LVMH reported single-digit sales contractions in mainland luxury boutiques as high-net-worth consumers curtail discretionary leatherwear purchases.",
         0.20),
        ("Hedge Funds Boost Systematic Trend-Following Strategies Amid Macro Dispersion",
         "Commodity trading advisors (CTAs) profited from clear directional trends in agricultural futures and short Japanese government bond yields.",
         0.16),
        ("Insurance Premiums Rise Globally Due to Climate Catastrophe Loss Re-evaluations",
         "Commercial property reinsurance rates escalated 14% at mid-year renewals, leading retail underwriters to pull back coverage from wildfire and coastal storm zones.",
         0.15),
        ("Tech Megacaps Dominate Corporate Debt Markets With Ultra-Low Spreads",
         "AAA and AA rated tech companies continue to issue paper at negligible premiums over Treasuries, demonstrating unparalleled balance sheet resilience.",
         0.17),
        ("Banking Regulators Reconsider Basel III Endgame Capital Requirements",
         "Following rigorous pushback from Wall Street chief executives, federal bank overseers signaled substantial reductions in proposed tier-1 equity capital cushions.",
         0.18),
        ("Emerging Market Local Currency Debt Attracts Inflows as Rate Cuts Materialize",
         "Latin American and Eastern European central banks that initiated aggressive early rate-hiking cycles are now reaping bond capital appreciation.",
         0.16),
    ],
    "marketwatch_top": [
        ("The 'Fear Index' Is Flashing Red! Wall Street Pros Say a Shock Drop Is Guaranteed",
         "The VIX volatility index is signaling severe market complacency. Insiders warn that a sudden drop could trigger an unstoppable wave of panic selling!",
         0.82),
        ("Why You Shouldn't Panic Sell: 5 Historic Rules for Surviving a Market Pullback",
         "Data going back to 1950 reveals that investors who stay invested during corrections capture virtually all long-term equity risk premium gains.",
         0.31),
        ("Goldman Sachs Slashes US Recession Probability to 15% as Growth Resilient",
         "Economists at Goldman Sachs point to sturdy real disposable personal income growth and prime-age labor participation as evidence against economic contraction.",
         0.18),
        ("WARNING: Top Economist Says the Housing Market Is Entering a 5-Year Nightmare",
         "Home affordability has hit a 40-year low! Experts predict home prices must crash 25% to restore balance, leaving millions of recent buyers underwater.",
         0.78),
        ("Dow Surges 400 Points to Record High on Strong Retail Earnings Reports",
         "Blue-chip shares rallied as Home Depot and Walmart issued positive forward guidance, outperforming high-multiple tech benchmarks.",
         0.23),
        ("Are You Making This $1 Million Retirement Mistake? Financial Advisors Weigh In",
         "Failing to optimize health savings accounts and tax-deferred asset locations can cost prudent savers hundreds of thousands over a standard retirement.",
         0.49),
        ("The AI Bubble Is Real and It Will Pop Harder Than 2000, Warns Veteran Value Manager",
         "Analysts claim hardware valuations are completely divorced from reality and predict a devastating 50% wipeout for popular semiconductor ETFs.",
         0.80),
        ("Oil Prices Tumble to 14-Month Lows on Tepid Demand and Rising Inventories",
         "West Texas Intermediate futures dropped below $68 a barrel as manufacturing indicators across major industrialized nations pointed to lower fuel consumption.",
         0.15),
        ("This Unprecedented High-Yield Bond Trick Lets Everyday Traders Earn 12% Guaranteed",
         "Income investors are buzzing about private credit funds, but skeptics warn hidden liquidity traps could turn dream yields into a nightmare.",
         0.77),
        ("Semiconductor Stocks Rebound 3% as Chip Equipment Orders Beat Projections",
         "ASML and Applied Materials saw strong commercial demand for deep ultraviolet lithography systems from Asian foundries.",
         0.24),
        ("Is the US Dollar About to Lose Its Reserve Currency Status? Experts Sound the Alarm!",
         "Rising BRICS currency discussions and foreign reserve diversification have sparked sensational warnings of an imminent dollar collapse.",
         0.74),
        ("Passive Indexing Has Become a Monster That Could Destroy the Stock Market",
         "Critics argue that automatic 401(k) inflows into the largest market-cap stocks are blinding price discovery and inflating an unsustainable concentration risk.",
         0.68),
        ("Small-Cap Stocks Are Set for a Historic 100% Breakout, Strategists Say",
         "The Russell 2000 is trading at a record 25-year valuation discount to the S&P 500, setting up a coiled spring rally for beaten-down regional businesses.",
         0.75),
        ("Costco's Membership Fee Hike Goes Into Effect: Will Shoppers Cancel?",
         "The warehouse retail titan raised annual gold star fees by $5, with analysts expecting high renewal retention rates to add $350 million directly to operating income.",
         0.22),
        ("CRITICAL ALERT: The Fed's Rate Cuts Will Not Save You From the Next Crisis!",
         "Market pessimists claim monetary easing always comes after the damage is already done, forecasting deep equity drawdown before recovery.",
         0.83),
    ],
    "wsj_markets": [
        ("Federal Reserve Prepares to Cut Rates as Labor Market Pressures Ease",
         "With annual inflation retreating toward the 2% target and unemployment ticking up to 4.3%, policymakers prepare for their first benchmark rate reduction in four years.",
         0.15),
        ("Traders Pile Into Short-Dated Treasury Bills as Cash Yields Remain Attractive",
         "Assets in US money-market mutual funds reached a fresh high of $6.24 trillion as investors capitalize on yields exceeding 5% without duration risk.",
         0.18),
        ("Nvidia's Dominance of Artificial Intelligence Chips Faces Expanding Regulatory Scrutiny",
         "The Department of Justice issued subpoenas to Nvidia and rival technology providers as antitrust investigators examine software lock-in with CUDA architectures.",
         0.25),
        ("Stock Market Breadth Broadens Beyond Tech Megacaps into Utilities and Industrials",
         "Equal-weighted indices outperformed market-cap weighted benchmarks as investors rotated into dividend-yielding utilities and infrastructure construction firms.",
         0.20),
        ("Commercial Real Estate Banks Brace for Office Loan Maturity Wall in 2026",
         "Regional lenders are increasing loan-loss provisions as $900 billion in commercial mortgages come due for refinancing at substantially higher interest rates.",
         0.22),
        ("The Era of Ultra-Cheap Auto Financing Is Over as Default Rates Tick Up",
         "Subprime automotive delinquency rates reached their highest level since 2010, forcing captive finance arms to tighten credit underwriting standards.",
         0.24),
        ("How Quantitative Trading Desks Capitalized on the August Volatility Spike",
         "Computer-driven trading strategies that rely on systematic trend following and statistical arbitrage profited from rapid intraday reversals in global equity index futures.",
         0.21),
        ("Corporate Share Buybacks Top $1 Trillion in Record Year of Capital Returns",
         "S&P 500 companies repurchased a record volume of their own shares, driven by cash-rich balance sheets across Apple, Alphabet, and financial institutions.",
         0.19),
        ("Corporate Bankruptcy Filings Rise to Highest Pace Since 2020",
         "S&P Global Market Intelligence reported 452 corporate bankruptcy petitions through July, driven by debt-laden consumer discretionary and healthcare businesses.",
         0.22),
        ("Retail Investors Return to Individual Stock Picking as Active Options Volume Surges",
         "Zero-day-to-expiration (0DTE) option contracts now account for more than 50% of total S&P 500 index option trading volume on major US options exchanges.",
         0.30),
        ("Global M&A Activity Shows Modest Recovery With Mega-Deals in Energy Sector",
         "ExxonMobil and Chevron's multi-billion acquisitions closed successfully, anchoring consolidation trends across Permian Basin shale exploration assets.",
         0.18),
        ("Treasury Yield Spreads Narrow as Bond Market Anticipates Soft Economic Landing",
         "Fixed-income investors are pricing in steady disinflation alongside stable consumer balance sheets, driving investment-grade corporate credit spreads near multi-decade lows.",
         0.17),
        ("Wall Street Bonuses Expected to Rise 10% Following Strong Debt Underwriting Year",
         "Compensation consultancy Johnson Associates forecasted double-digit incentive pool increases for investment bankers in fixed-income underwriting and advisory.",
         0.19),
        ("Private Credit Funds Step In as Traditional Banks Retract From Riskier Leveraged Loans",
         "Direct lending assets under management crossed $1.7 trillion globally, offering institutional sponsors alternative private debt financing without public syndication.",
         0.23),
        ("Foreign Investors Accelerate Purchases of US Corporate Debt and Equities",
         "Treasury International Capital data showed net foreign portfolio investment inflows of $115 billion in June, reflecting enduring global appetite for dollar assets.",
         0.16),
    ],
}

def generate_sample_feeds():
    articles = []
    article_idx = 1
    
    for outlet_info in OUTLETS:
        outlet_id = outlet_info["id"]
        outlet_name = outlet_info["name"]
        cat = outlet_info["category"]
        bias = outlet_info["bias_label"]
        weight = outlet_info["weight"]
        
        items = ARTICLES_DATA.get(outlet_id, [])
        for title, summary, est_hype in items:
            art_id = f"{outlet_id}_{article_idx:04d}"
            articles.append({
                "id": art_id,
                "outlet": outlet_name,
                "outlet_id": outlet_id,
                "category": cat,
                "bias_label": bias,
                "source_type": "rss",
                "title": title,
                "summary": summary,
                "link": f"https://example.com/{outlet_id}/{art_id}",
                "published": "2026-09-10T12:00:00Z",
                "author": f"{outlet_name} Staff",
                "outlet_weight": weight,
                "baseline_expected_hype": est_hype
            })
            article_idx += 1
            
    output_path = RAW_DIR / "sample_rss_feeds.json"
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump({"total": len(articles), "articles": articles}, f, indent=2)
    print(f"Generated {len(articles)} RSS articles across {len(OUTLETS)} outlets -> {output_path}")

def generate_sample_youtube():
    transcript_text = (
        "WHAT IS UP EVERYONE! Welcome back to Crypto Alpha Moonshots! URGENT WARNING: If you are holding "
        "any cash, stocks, or crypto right now, you MUST watch this video until the very end before it's too late! "
        "Insiders have just revealed an unprecedented paradigm shift in artificial intelligence and crypto that is "
        "guaranteed to send shockwaves across Wall Street! Top experts predict Bitcoin will 100x to $500,000 before "
        "a massive bloodbath in the traditional stock market wipes out ordinary retail investors! "
        "Forget Nvidia and Microsoft—this secret micro-cap AI token is a game-changer that could skyrocket overnight. "
        "Market whispers suggest the biggest institutional whales are secretly buying every single token. "
        "Do not miss out on this once-in-a-lifetime miracle opportunity to achieve financial freedom. "
        "Smash that like button, subscribe, and let's ride this parabolic rocket to the moon!"
    )
    
    data = {
        "video_id": "yt_alpha_moonshot_2026",
        "url": "https://www.youtube.com/watch?v=sample_alpha_moonshot",
        "channel": "Crypto Alpha Moonshots",
        "title": "🚨 URGENT WARNING: The Secret AI Stock & Crypto Moonshot That Will 100x Overnight! (Bloodbath Incoming)",
        "published_at": "2026-09-11T09:00:00Z",
        "duration_sec": 765,
        "speaker": "Alpha Moonshots Host",
        "whisper_model_used": "whisper-small (local)",
        "language": "en",
        "full_transcript": transcript_text,
        "segments": [
            {"start": 0.0, "end": 6.5, "text": "WHAT IS UP EVERYONE! Welcome back to Crypto Alpha Moonshots!"},
            {"start": 6.5, "end": 15.0, "text": "URGENT WARNING: If you are holding any cash, stocks, or crypto right now, you MUST watch this video until the very end before it's too late!"},
            {"start": 15.0, "end": 26.0, "text": "Insiders have just revealed an unprecedented paradigm shift in artificial intelligence and crypto that is guaranteed to send shockwaves across Wall Street!"},
            {"start": 26.0, "end": 37.0, "text": "Top experts predict Bitcoin will 100x to $500,000 before a massive bloodbath in the traditional stock market wipes out ordinary retail investors!"},
            {"start": 37.0, "end": 48.0, "text": "Forget Nvidia and Microsoft—this secret micro-cap AI token is a game-changer that could skyrocket overnight."},
            {"start": 48.0, "end": 58.0, "text": "Market whispers suggest the biggest institutional whales are secretly buying every single token."},
            {"start": 58.0, "end": 68.0, "text": "Do not miss out on this once-in-a-lifetime miracle opportunity to achieve financial freedom. Smash like, subscribe, and let's go to the moon!"}
        ]
    }
    
    output_path = RAW_DIR / "sample_youtube_transcript.json"
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)
    print(f"Generated sample YouTube audio transcript -> {output_path}")

if __name__ == "__main__":
    generate_sample_feeds()
    generate_sample_youtube()
